CREATE TABLE USERDATA(
    USERNAME TEXT PRIMARY KEY,
    FULLNAME TEXT,
    EMAIL TEXT,
    PASSWORD TEXT
);

INSERT INTO USERDATA (USERNAME, FULLNAME, EMAIL, PASSWORD) VALUES ('test12', 'Test Jakab', 'test@test.com', 'Password123');

